// Generated by CoffeeScript 1.7.1
var BSON, Db, Server, client, db, frequest, gitdata, lang, location, mongo, page, request, server;

mongo = require("mongodb");

Server = mongo.Server;

Db = mongo.Db;

BSON = mongo.BSONPure;

server = new Server("localhost", 27017, {
  auto_reconnect: true
});

db = new Db("githubdb", server);

db.open(function(err, db) {
  if (!err) {
    return console.log("Connected to 'githubdb' database");
  }
});

request = require("request-json");

frequest = require("request");

client = request.newClient('https://api.github.com/');

lang = 'ruby';

location = 'London';

page = 4;

gitdata = function(lang, location, page) {
  return client.get('search/users?q=location:' + location + '+language:' + lang + '&page=' + page, function(err, res, body) {
    var profile, profilearray, _i, _len, _results;
    if (err) {
      return console.log(err);
    } else {
      console.log('Total Users found: ' + body.total_count);
      profilearray = body.items;
      _results = [];
      for (_i = 0, _len = profilearray.length; _i < _len; _i++) {
        profile = profilearray[_i];
        _results.push(db.collection("profiles", function(err, collection) {
          var options;
          if (err) {
            console.log(err);
          } else {
            options = {
              url: profile.url,
              headers: {
                'User-Agent': 'Kontak'
              },
              json: true
            };
            frequest(options, function(error, responce, body) {
              if (error) {
                return console.log(error);
              } else if (body.email === null) {
                return null;
              } else if (body.email === "") {
                return null;
              } else if (body.site_admin === true) {
                return null;
              } else {
                return collection.insert(body, {
                  safe: true
                }, function(err, result) {});
              }
            });
          }
          return console.log("Adding GitHub user " + profile.login + " to the DB");
        }));
      }
      return _results;
    }
  });
};

gitdata(lang, location, page);
