// Generated by CoffeeScript 1.7.1
var client, gitdata, lang, location, page, request;

request = require('request-json');

client = request.newClient('https://api.github.com/');

lang = 'ruby';

location = 'london';

page = 1;

gitdata = function(lang, location, page) {
  return client.get('search/users?q=location:' + location + '+language:' + lang + '&page=' + page, function(err, res, body) {
    console.log('Total Users found: ' + body.total_count);
    return console.log(body.items[0]);
  });
};

gitdata(lang, location, page);
