// Generated by CoffeeScript 1.7.1
var mailOptions, nodemailer, smtpTransport;

nodemailer = require("nodemailer");

smtpTransport = nodemailer.createTransport("SMTP", {
  service: "Gmail",
  auth: {
    user: "snevets@gmail.com",
    pass: "XXXX"
  }
});

mailOptions = {
  from: "Fred Foo ✔ <foo@blurdybloop.com>",
  to: "snevets@gmail.com",
  subject: "SUBJECT LINE",
  text: "THIS IS TEXT",
  html: "<b>THIS IS HTML</b>"
};

smtpTransport.sendMail(mailOptions, function(error, response) {
  if (error) {
    return console.log(error);
  } else {
    return console.log("Message sent: " + response.message);
  }
});

smtpTransport.close();
