// Generated by CoffeeScript 1.7.1
var BSON, Db, Server, db, mongo, server;

mongo = require("mongodb");

Server = mongo.Server;

Db = mongo.Db;

BSON = mongo.BSONPure;

server = new Server("localhost", 27017, {
  auto_reconnect: true
});

db = new Db("githubdb", server);

db.open(function(err, db) {
  if (!err) {
    return console.log("Connected to 'githubdb' database");
  }
});

db.collection("profiles", function(err, collection) {
  return collection.insert(wines, {
    safe: true
  }, function(err, result) {});
});
