// Generated by CoffeeScript 1.7.1
var app, cors, express, http, profiles;

express = require("express");

http = require("http");

cors = require("cors");

profiles = require("./routes/profiles");

app = express();

app.use(cors());

app.get("/profiles", profiles.findAll);

app.get("/profiles/:id", profiles.findById);

app.post("/profiles", profiles.addProfile);

app.put("/profiles/:id", profiles.updateProfile);

app["delete"]("/wines/:id", profiles.deleteProfile);

app.listen(3000);

console.log("Listening on port 3000 ;)");
