// Generated by CoffeeScript 1.7.1
var Profile, mongoose;

mongoose = require("mongoose");

Profile = require("../models/profile");

exports.sendEmail = function(req, res) {
  var Emailer, data, emailer, options, profile;
  profile = req.body;
  console.log("Emailing: " + JSON.stringify(profile.name));
  options = {
    to: {
      email: "snevets@gmail.com",
      name: profile.name,
      subject: "FAO:  - Award Winning Financial Tech Startup - London",
      template: "test"
    }
  };
  data = {
    name: profile.name.split(" ")[0],
    url: profile.html_url
  };
  Emailer = require("../../lib/emailer");
  emailer = new Emailer(options, data);
  return emailer.send(function(err, result) {
    if (err) {
      return console.log(err);
    } else {
      console.log(result);
      res.send("Email sent to: " + options.to.name + " email:" + options.to.email);
      return Profile.update({
        _id: profile._id
      }, {
        $push: {
          messages: {
            author: 'Steven',
            body: options.to.template
          }
        }
      }, {
        upsert: true
      }, function(err, data) {});
    }
  });
};
