// Generated by CoffeeScript 1.7.1
var Profile, emailSchema, exports, mongoose;

mongoose = require("mongoose");

emailSchema = new mongoose.Schema({
  client: String,
  role: String,
  html: String
});

Profile = mongoose.model('Email', profileSchema);

exports = module.exports = Email;
