// Generated by CoffeeScript 1.7.1
var Template, exports, mongoose, templateSchema;

mongoose = require("mongoose");

templateSchema = new mongoose.Schema({
  client: String,
  role: String,
  subject: String,
  html: String
});

Template = mongoose.model('Template', templateSchema);

exports = module.exports = Template;
